version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: PostgresDB
    environment:
      POSTGRES_DB: "PostgresDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /storage/PostgresDB:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
